export const unitAmenities = [
  "Air Conditioning",
  "Cable Ready",
  "Fireplace",
  "Storage Units",
  "Washer/Dryer",
  "Washer/Dryer Hookup",
  "Heating",
  "Security System",
  "Ceiling Fans",
  "Double Vanities",
  "High Speed Internet Access",
  "Satellite TV",
  "Sprinkler System",
  "Tub/Shower",
  "Surround Sound",
  "Wi-Fi",
  "Framed Mirrors",
  "Handrails",
  "Intercom",
  "Smoke Free",
  "Trash Compactor",
  "Vaccuum System",
  "Wheelchair Accessible (Rooms)",
];

export const kitchenAmenities = [
  "Dishwasher",
  "Disposal",
  "Microwave",
  "Eat-in Kitchen",
  "Kitchen",
  "Granite Countertops",
  "Ice Maker",
  "Refrigerator",
  "Oven",
  "Stainless Steel Appliances",
  "Range",
  "Coffee System",
  "Freezer",
];

export const outdoorAmenities = [
  "Balcony",
  "Yard",
  "Grill",
  "Deck",
  "Dock",
  "Garden",
  "Greenhouse",
  "Lawn",
  "Patio",
  "Porch",
];

export const livingSpaceAmenities = [
  "Bay Window",
  "Tile Floors",
  "Crown Molding",
  "Hardwood Floors",
  "Vaulted Ceiling",
  "Sunroom",
  "Views",
  "Walk-In Closets",
  "Carpet",
  "Attic",
  "Basement",
  "Family Room",
  "Furnished",
];
